// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8zG9ZLnejAVVwCwBRa-i0eBK0YRDRCww',
    appId: '1:276086092198:android:6315c3ce8f9a0894cb9f67',
    messagingSenderId: '276086092198',
    projectId: 'blaze-taxi-662b8',
    databaseURL: 'https://blaze-taxi-662b8-default-rtdb.firebaseio.com',
    storageBucket: 'blaze-taxi-662b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBquW0WNgUKpfTwERh9LUSeTBUVKwzeiYs',
    appId: '1:276086092198:ios:9132a54447ed94bbcb9f67',
    messagingSenderId: '276086092198',
    projectId: 'blaze-taxi-662b8',
    databaseURL: 'https://blaze-taxi-662b8-default-rtdb.firebaseio.com',
    storageBucket: 'blaze-taxi-662b8.appspot.com',
    androidClientId: '276086092198-ev67s7ul86e1qk1b32cai4egsuvvrhvc.apps.googleusercontent.com',
    iosClientId: '276086092198-jpvgs4i8u9dqurde8vqo6okldlb8dett.apps.googleusercontent.com',
    iosBundleId: 'com.isoftdesing.blazeDriver',
  );
}
